title: Soluções em Sistemas Embarcados
logo: images/bap.png
description: Página voltada para apresentação do portifólio de projetos desenvolvidos
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
